'use client'

export default function Head({ params }) {
    return (
        <>
            <title>Vpanel</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta charSet="UTF-8" />
            <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        </>
    );
  }
  